# Project language
language: php

# Language versions to test agains
php:
    - '7.0'
#    - '7.1'
#    - nightly

# Special addons
addons:
    # Code coverage
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN
        coverage_report: $TRAVIS_BUILD_DIR/build/logs/clover.xml

# Save cache of dependencies
cache:
    directories:
        - vendor/

# Install dependencies
install:
    - composer install

# Start tests
script:
    - vendor/bin/phpunit -v --bootstrap phpunit.php --configuration phpunit.xml --coverage-text --coverage-clover=$TRAVIS_BUILD_DIR/build/logs/clover.xml --colors=never

# If successfull, report coverage
after_success:
    - vendor/bin/test-reporter